export const data = {
  en: {
    config: {
      name: 'Bahyu-Sella',
      bgm: 'https://ia802805.us.archive.org/4/items/MarryYourDaughter_525/BrianMcknight-MarryYourDaughterlyrics.mp3',
    },
    header: {
      bgImageLandscape: [require('./assets/images/bg-1.jpg'), require('./assets/images/bg-2.jpg'), require('./assets/images/bg-3.jpg')],
      bgImagePortrait: [require('./assets/images/bg-4.jpg'), require('./assets/images/bg-5.jpg'), require('./assets/images/bg-6.jpg')],
      bridegroom: 'Bahyu & Sella',
      desc: 'ARE GETTING MARRIED',
      date: 'November 3TH, 2024',
      timestamp: 1730566800000,
      ongoing: 'ONGOING',
      days: 'DAYS',
      hours: 'HOURS',
      minutes: 'MINUTES',
      seconds: 'SECONDS',
      line1: 'Kindly deliver to: Mr. / Mrs. / Ms.',
      line2: 'We invite you to celebrate our wedding',
      button: 'Open Invitation',
    },
    navbar: {
      brand: 'B & S',
      nav: [
        { to: 'header', text: 'Home' },
        { to: 'couple', text: 'Couple' },
        { to: 'events', text: 'Events' },
        { to: 'moment', text: 'Moment' },
        { to: 'location', text: 'Location' },
      ],
    },
    couple: {
      title: 'Meet Happy Couple',
      groom: {
        name: 'Bahyu Sanciko',
        photo: require('./assets/images/couple/1.png'),
        status: 'GROOM',
        socmed: {
          facebook: 'https://www.facebook.com/bahyusanciko/',
          twitter: 'https://x.com/bhysnck',
          instagram: 'https://www.instagram.com/bahyusanciko/',
        },
        description: 'The first son of Alm. Edi and Mayasnida',
      },
      bride: {
        name: 'Sella Purwita Sari',
        photo: require('./assets/images/couple/2.png'),
        status: 'BRIDE',
        socmed: {
          facebook: 'https://www.facebook.com/profile.php?id=100008708643415',
          twitter: 'https://x.com/sellaprwt',
          instagram: 'https://www.instagram.com/sellaprwt/',
        },
        description: 'The third daughter of Taryono and Alm. Rosmini',
      },
    },
    events: {
      reception: {
        type: 'reception',
        foto: require('./assets/images/events/reception.jpg'),
        title: 'THE RECEPTION',
        date: 'Sunday, November 3th 2023',
        time: '10.00 AM - 04.00 PM',
        address: {
          line1: 'Villa Srimaganti',
          line2: '. Raya Pkp No.34, RT.2/RW.8, Klp. Dua Wetan',
          line3: 'Kec. Ciracas, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13720',
        },
      },
    },
    moment: {
      images: [
        // {
        //   src: require('./assets/images/moment/1.jpg'),
        //   thumbnail: require('./assets/images/moment/thumbnails/1.jpg'),
        //   thumbnailWidth: 320,
        //   thumbnailHeight: 200,
        // },
        // {
        //   src: require('./assets/images/moment/2.jpg'),
        //   thumbnail: require('./assets/images/moment/thumbnails/2.jpg'),
        //   thumbnailWidth: 240,
        //   thumbnailHeight: 320,
        // },
        // {
        //   src: require('./assets/images/moment/3.jpg'),
        //   thumbnail: require('./assets/images/moment/thumbnails/3.jpg'),
        //   thumbnailWidth: 320,
        //   thumbnailHeight: 200,
        // },
        // {
        //   src: require('./assets/images/moment/4.jpg'),
        //   thumbnail: require('./assets/images/moment/thumbnails/4.jpg'),
        //   thumbnailWidth: 240,
        //   thumbnailHeight: 320,
        // },
        // {
        //   src: require('./assets/images/moment/5.jpg'),
        //   thumbnail: require('./assets/images/moment/thumbnails/5.jpg'),
        //   thumbnailWidth: 320,
        //   thumbnailHeight: 200,
        // },
        // {
        //   src: require('./assets/images/moment/6.jpg'),
        //   thumbnail: require('./assets/images/moment/thumbnails/6.jpg'),
        //   thumbnailWidth: 240,
        //   thumbnailHeight: 320,
        // },
        // {
        //   src: require('./assets/images/moment/7.jpg'),
        //   thumbnail: require('./assets/images/moment/thumbnails/7.jpg'),
        //   thumbnailWidth: 320,
        //   thumbnailHeight: 200,
        // },
        // {
        //   src: require('./assets/images/moment/8.jpg'),
        //   thumbnail: require('./assets/images/moment/thumbnails/8.jpg'),
        //   thumbnailWidth: 320,
        //   thumbnailHeight: 200,
        // },
        // {
        //   src: require('./assets/images/moment/9.jpg'),
        //   thumbnail: require('./assets/images/moment/thumbnails/9.jpg'),
        //   thumbnailWidth: 240,
        //   thumbnailHeight: 320,
        // },
        // {
        //   src: require('./assets/images/moment/10.jpg'),
        //   thumbnail: require('./assets/images/moment/thumbnails/10.jpg'),
        //   thumbnailWidth: 320,
        //   thumbnailHeight: 200,
        // },
        // {
        //   src: require('./assets/images/moment/11.jpg'),
        //   thumbnail: require('./assets/images/moment/thumbnails/11.jpg'),
        //   thumbnailWidth: 240,
        //   thumbnailHeight: 320,
        // },
        // {
        //   src: require('./assets/images/moment/12.jpg'),
        //   thumbnail: require('./assets/images/moment/thumbnails/12.jpg'),
        //   thumbnailWidth: 320,
        //   thumbnailHeight: 200,
        // },
        // {
        //   src: require('./assets/images/moment/13.jpg'),
        //   thumbnail: require('./assets/images/moment/thumbnails/13.jpg'),
        //   thumbnailWidth: 240,
        //   thumbnailHeight: 320,
        // },
        // {
        //   src: require('./assets/images/moment/14.jpg'),
        //   thumbnail: require('./assets/images/moment/thumbnails/14.jpg'),
        //   thumbnailWidth: 320,
        //   thumbnailHeight: 240,
        // },
        // {
        //   src: require('./assets/images/moment/15.jpg'),
        //   thumbnail: require('./assets/images/moment/thumbnails/15.jpg'),
        //   thumbnailWidth: 240,
        //   thumbnailHeight: 320,
        // },
        // {
        //   src: require('./assets/images/moment/16.jpg'),
        //   thumbnail: require('./assets/images/moment/thumbnails/16.jpg'),
        //   thumbnailWidth: 320,
        //   thumbnailHeight: 240,
        // },
      ],
    },
    location: {
      maps: 'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15861.643214787087!2d106.8865514!3d-6.3408067!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e69ece0f99a5e9b%3A0x168b992d3633c0cf!2sVilla%20Srimanganti!5e0!3m2!1sen!2sid!4v1723555123443!5m2!1sen!2sid',
    },
  },
};
